server:
  port: 9090 # 端口

spring:
  application:
    name: service-consumer # 应用名称
  security:
    user:
      name: root
      password: root
# 配置 Eureka Server 注册中心
#eureka:
#  client:
#    register-with-eureka: false # 是否将自己注册到注册中心，默认为true
#    registry-fetch-interval-seconds: 10 # 表示 Eureka Client 间隔多久去服务器拉取注册信息，默认为 30 秒
#    service-url: # 设置服务注册中心地址
#      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/

# 负载均衡策略
# service-provider 为调用的服务的名称
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    listOfServers: http://localhost:7070,http://localhost:7071

# 关闭 Eureka 实现 Ribbon 点对点直连
ribbon:
  eureka:
    enabled: false # false：关闭，true：开启