server:
  port: 9094                                # 项目访问端口，默认 8080
  servlet:
    context-path: /shop-sso

# Spring
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 指定 druid 连接池以及 druid 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1                       # 初始连接数
      max-active: 20                        # 最大连接数
      max-idle: 20                          # 最大空闲
      min-idle: 1                           # 最小空闲
      max-wait: 60000                       # 最长等待时间
  ## redis 配置
  redis:
    host: 192.168.203.131
    password: root
    port: 6379

# MyBatis
mybatis:
  # 配置 MyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.yjxxt.sso.pojo
  # 配置 MyBatis Mapper 映射文件
  mapper-locations: classpath:mapper/*.xml

# Mybatis SQL 打印(方法接口所在的包，不是 Mapper.xml 所在的包)
logging:
  level:
    com.yjxxt.sso.mapper: debug


#  Dubbo Provider环境配置
dubbo:
  ## 应用名
  application:
    name: shop-sso
  ## 注册中心
  registry:
    address: zookeeper://192.168.203.134:2181
  ## 注册服务采用的协议
  protocol:
    port: 20881
    name: dubbo
  ## 配置服务所在包范围
  scan:
    base-packages: com.yjxxt.sso.service


#用户票据key
user.ticket: user:userTicket